let STATIONS=[];let selectedImage=null;
const $=id=>document.getElementById(id);
fetch('stations.json').then(r=>r.json()).then(d=>{STATIONS=d; $('manualHelp').textContent=`${d.length} stations chargées depuis Excel.`});
function normalize(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[|\[\]{}]/g,' ').replace(/[.,;:]/g,' ').replace(/P\s*\.?\s*M\s*\.?/g,'PM').replace(/JEANNE\s*MANCE/g,'JEANNE MANCE').replace(/MANCEN/g,'MANCE N').replace(/([A-Z])\.([A-Z])/g,'$1 $2').replace(/0/g,'O0').replace(/\s+/g,' ').trim()}
function normStrict(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[.,;:]/g,' ').replace(/P\s*\.?\s*M\s*\.?/g,'PM').replace(/[^A-Z0-9\-\/ ]+/g,' ').replace(/\s+/g,' ').trim()}
function cleanLineForStation(line){let l=normStrict(line); const pm=l.indexOf('PM'); if(pm>0) l=l.slice(pm); l=l.replace(/\bN\s*\d{1,5}\b.*$/,'').replace(/\bS\s*\d+\b.*$/,'').replace(/\bNIVEAU\s*\d+\b/g,'').replace(/\s+/g,' ').trim(); return l}
function tokens(s){return normStrict(s).split(/\s+/).filter(t=>t.length>=3&&!['PM','HALL','NIV','NIVEAU','PRES','PRET'].includes(t))}
function extractQueries(text){const lines=String(text||'').split(/\n+/).map(x=>x.trim()).filter(Boolean); const q=[];
 for(const raw of lines){ const n=normStrict(raw); if(n.includes('PM') || n.includes('HALL') || /\d{1,2}[- ]\d{2,5}/.test(n)){ let c=cleanLineForStation(raw); if(c && c.length>2) q.push(c); }}
 const all=normStrict(text); const codes=all.match(/\b\d{1,2}\s*[- ]\s*\d{2,5}[A-Z]?\b/g)||[]; codes.forEach(c=>q.push(c.replace(/\s+/g,'')));
 // expressions fiables fréquentes
 ['JEANNE MANCE','VIGER','MELK','POSTE CANADA','ST ANTOINE','SAINT ANTOINE','VESTI','ESC'].forEach(k=>{if(all.includes(k)) q.push(k)});
 return [...new Set(q.map(x=>x.trim()).filter(x=>x.length>=3 && !/^S\s*\d+$/.test(x) && !/^N\s*\d+$/.test(x)))]}
function scoreStation(query, st){const q=normStrict(query); const station=normStrict(st.station); const hay=normStrict([st.station,st.identification,st.description,st.localisation,st.niveau].join(' ')); let score=0;
 if(!q || /^S\s*\d+$/.test(q)) return 0;
 if(hay.includes(q)) score+=100; if(q.includes(station)&&station.length>5) score+=120; if(station.includes(q)&&q.length>5) score+=110;
 const code=q.match(/\b\d{1,2}[- ]\d{2,5}[A-Z]?\b/); if(code){const c=code[0].replace(/\s/g,''); if(hay.replace(/\s/g,'').includes(c)) score+=140;}
 const qt=tokens(q); const stt=tokens(station); for(const t of qt){ if(stt.includes(t)) score+=35; else if(hay.includes(t)) score+=15; }
 if(q.includes('JEANNE') && hay.includes('JEANNE')) score+=80; if(q.includes('MANCE')&&hay.includes('MANCE'))score+=80;
 if(q.includes('VIGER') && hay.includes('VIGER'))score+=70; if(q.includes('MELK')&&hay.includes('MELK'))score+=70;
 return score}
function searchSmart(raw){const queries=extractQueries(raw); if(normStrict(raw).length>0 && !queries.includes(normStrict(raw))) queries.unshift(normStrict(raw)); let scored=[]; for(const st of STATIONS){let best=0,bq=''; for(const q of queries){const s=scoreStation(q,st); if(s>best){best=s;bq=q}} if(best>0) scored.push({...st,score:best,matched:bq});} scored.sort((a,b)=>b.score-a.score); return {queries,scored}}
function renderResult(result, auto=false){const {queries,scored}=searchSmart(result); $('query').textContent='Code / ligne détectée : '+(queries[0]||result||'—'); const box=$('result'); box.innerHTML=''; if(scored[0] && scored[0].score>=120 && (!scored[1] || scored[0].score-scored[1].score>=25 || scored[0].score>=200)){box.innerHTML=stationCard(scored[0]); return;} box.innerHTML=`<div class="warn"><b>Résultat non confirmé.</b><br>Je préfère afficher les possibilités au lieu d'une mauvaise station.</div>`+scored.slice(0,8).map(st=>`<div class="item" data-n="${st.numero}"><b>${st.station}</b> — ${st.description}<br><small>Score ${st.score} • trouvé par : ${st.matched}</small></div>`).join(''); box.querySelectorAll('.item').forEach(el=>el.onclick=()=>{const st=scored.find(s=>String(s.numero)===el.dataset.n); box.innerHTML=stationCard(st)});}
function stationCard(st){return `<div class="ok"><h2>✅ Station trouvée</h2><div class="bigdesc">${esc(st.description)}</div><div class="meta"><div class="label">N°</div><div>${esc(st.numero)}</div><div class="label">Station</div><div>${esc(st.station)}</div><div class="label">Identification</div><div>${esc(st.identification||'Non identifié')}</div><div class="label">Étage</div><div>${esc(st.etage)}</div><div class="label">Niveau</div><div>${esc(st.niveau)}</div><div class="label">Secteur</div><div>${esc(st.localisation)}</div></div></div>`}
function esc(s){return String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
$('photo').addEventListener('change',e=>{const f=e.target.files[0]; if(!f)return; selectedImage=new Image(); selectedImage.onload=()=>drawImages(selectedImage); selectedImage.src=URL.createObjectURL(f);});
function drawImages(img){drawCanvas($('fullCanvas'),img,0,0,img.width,img.height,300); // crop line: upper part of screen; wider than previous versions
 const sx=img.width*0.05, sy=img.height*0.30, sw=img.width*0.90, sh=img.height*0.25; drawCanvas($('cropCanvas'),img,sx,sy,sw,sh,420); $('status').textContent='Photo chargée. Lance OCR.'}
function drawCanvas(c,img,sx,sy,sw,sh,targetW){const scale=targetW/sw; c.width=targetW;c.height=Math.round(sh*scale);const ctx=c.getContext('2d');ctx.imageSmoothingEnabled=true;ctx.drawImage(img,sx,sy,sw,sh,0,0,c.width,c.height)}
async function runOCR(){if(!selectedImage){alert('Ajoute une photo.');return} $('status').textContent='OCR en cours...'; const canvases=[$('cropCanvas'),$('fullCanvas')]; let all=''; for(const c of canvases){const r=await Tesseract.recognize(c,'fra+eng',{logger:m=>{if(m.status)$('status').textContent=`OCR : ${m.status} ${m.progress?Math.round(m.progress*100)+'%':''}`}}); all+='\n'+r.data.text;} $('ocrText').textContent=all; $('status').textContent='OCR terminé. Recherche terminée.'; renderResult(all,true)}
$('ocrBtn').onclick=runOCR; $('manualBtn').onclick=()=>renderResult($('manual').value,false); $('manual').addEventListener('keydown',e=>{if(e.key==='Enter')renderResult($('manual').value,false)}); $('resetBtn').onclick=()=>location.reload();
